### ISSUE TITLE
Multiple test failures with Python 3.11.0b1

### ISSUE THREAD

**Issue by mgorny** [testing-cabal/fixtures#66]
The following tests are failing against Python 3.11.0b1:

```pytb
$ tox -e py311
/tmp/fixtures/.tox/py311/lib/python3.11/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/tmp/fixtures/.tox/py311/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
py311 develop-inst-noop: /tmp/fixtures
py311 installed: docutils==0.18.1,extras==1.0.0,-e git+https://github.com/testing-cabal/fixtures/@4a30fe9c8f81ab6d1133055b3c1830e4d86c8518#egg=fixtures,mock==4.0.3,pbr==5.9.0,testtools==2.5.0
py311 run-test-pre: PYTHONHASHSEED='1983342538'
py311 run-test: commands[0] | python -m testtools.run fixtures.test_suite
<frozen runpy>:128: RuntimeWarning: 'testtools.run' found in sys.modules after import of package 'testtools', but prior to execution of 'testtools.run'; this may result in unpredictable behaviour
Tests running...
======================================================================
ERROR: fixtures.tests._fixtures.test_monkeypatch.TestMonkeyPatch.test_patch_classmethod_with_classmethod
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/fixtures/fixtures/tests/_fixtures/test_monkeypatch.py", line 203, in test_patch_classmethod_with_classmethod
    cls, = C.foo_cls()
    ^^^^
ValueError: too many values to unpack (expected 1)
======================================================================
FAIL: fixtures.tests._fixtures.test_monkeypatch.TestMonkeyPatch.test_patch_classmethod_with_boundmethod
----------------------------------------------------------------------
Failed expectation: {{{MismatchError: <class 'fixtures.tests._fixtures.test_monkeypatch.C'> is not None}}}
Failed expectation-1: {{{MismatchError: <class 'fixtures.tests._fixtures.test_monkeypatch.C'> is not None}}}

AssertionError: Forced Test Failure
======================================================================
FAIL: fixtures.tests._fixtures.test_popen.TestFakePopen.test_function_signature
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/fixtures/fixtures/tests/_fixtures/test_popen.py", line 145, in test_function_signature
    self.assertSetEqual(
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/case.py", line 1101, in assertSetEqual
    self.fail(self._formatMessage(msg, standardMsg))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/unittest/case.py", line 671, in fail
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Items in the second set but not the first:
'process_group' : Function signature of FakePopen doesn't match subprocess.Popen

Ran 139 tests in 2.032s
FAILED (failures=3)
ERROR: InvocationError for command /tmp/fixtures/.tox/py311/bin/python -m testtools.run fixtures.test_suite (exited with code 1)
_______________________________________________________________ summary _______________________________________________________________
ERROR:   py311: commands failed
```

**Comment by mgorny** [comment]
I guess this means that the old `classmethod` behavior was restored (?!)

**Comment by mgorny** [comment]
Well, it wasn't that hard. Filed #67 and #68 with the two fixes I needed to make the tests pass.

**Comment by stephenfin** [comment]
I've merged both of those. It would be good to add ci jobs for 3.11, though perhaps we can wait til GA for that. Closing as I think this has been addressed now

**Comment by mgorny** [comment]
Thanks! I'll make a PR to add 3.11.
